version: "3.9"

name: ESG

services:

  nginx:
      container_name: nginx
      image: nginx:latest
      ports:
        - 80:80
      networks:
        - Web-Netwok

networks:
  ESGNetwok:
    name: Web-Netwok
    
